#############################################################################
# Makefile for building: Tognazzi
# Generated by qmake (2.01a) (Qt 4.8.1) on: Fri Feb 14 14:50:28 2014
# Project:  Tognazzi.pro
# Template: app
# Command: /usr/local/qt/bin/qmake -o Makefile Tognazzi.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/local/Trolltech/Qt-4.8.1/mkspecs/linux-g++-64 -I. -I/usr/local/Trolltech/Qt-4.8.1/include/QtCore -I/usr/local/Trolltech/Qt-4.8.1/include/QtGui -I/usr/local/Trolltech/Qt-4.8.1/include -I$(ROOTSYS)/include -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1 -Wl,-rpath,/usr/local/Trolltech/Qt-4.8.1/lib
LIBS          = $(SUBLIBS)  -L/usr/local/Trolltech/Qt-4.8.1/lib -L/opt/local/root/lib -lCore -lCint -lRIO -lNet -lHist -lGraf -lGraf3d -lGpad -lTree -lRint -lPostscript -lMatrix -lPhysics -lMathCore -lThread -lGui -pthread -Wl,-rpath,/opt/local/root/lib -lm -ldl -rdynamic -lGQt -lQtGui -L/usr/local/Trolltech/Qt-4.8.1/lib -L/usr/X11R6/lib64 -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/local/qt/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		variableshandler.cpp \
		filereader.cpp \
		scurveanalysis.cpp \
		vtrimadjuster.cpp \
		vtrimgain.cpp \
		vtrimset.cpp \
		pixelselection.cpp \
		pixelsingle.cpp \
		umessanger.cpp \
		pixelselectionbutton.cpp \
		finetuner.cpp moc_mainwindow.cpp \
		moc_pixelselection.cpp \
		moc_pixelsingle.cpp \
		moc_pixelselectionbutton.cpp \
		moc_finetuner.cpp
OBJECTS       = main.o \
		mainwindow.o \
		variableshandler.o \
		filereader.o \
		scurveanalysis.o \
		vtrimadjuster.o \
		vtrimgain.o \
		vtrimset.o \
		pixelselection.o \
		pixelsingle.o \
		umessanger.o \
		pixelselectionbutton.o \
		finetuner.o \
		moc_mainwindow.o \
		moc_pixelselection.o \
		moc_pixelsingle.o \
		moc_pixelselectionbutton.o \
		moc_finetuner.o
DIST          = /usr/local/Trolltech/Qt-4.8.1/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/common/linux.conf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/common/gcc-base.conf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/common/gcc-base-unix.conf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/common/g++-base.conf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/common/g++-unix.conf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/default_pre.prf \
		/usr/local/root/include/rootlibs.pri \
		/usr/local/root/include/rootcintrule.pri \
		/usr/local/root/include/rootcint.pri \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/release.prf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/lex.prf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/include_source_dir.prf \
		Tognazzi.pro
QMAKE_TARGET  = Tognazzi
DESTDIR       = 
TARGET        = Tognazzi

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h ui_pixelselection.h ui_pixelsingle.h ui_finetuner.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Tognazzi.pro  /usr/local/Trolltech/Qt-4.8.1/mkspecs/linux-g++-64/qmake.conf /usr/local/Trolltech/Qt-4.8.1/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/common/linux.conf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/common/gcc-base.conf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/common/gcc-base-unix.conf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/common/g++-base.conf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/common/g++-unix.conf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/default_pre.prf \
		/usr/local/root/include/rootlibs.pri \
		/usr/local/root/include/rootcintrule.pri \
		/usr/local/root/include/rootcint.pri \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/release.prf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/lex.prf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/include_source_dir.prf \
		/usr/local/Trolltech/Qt-4.8.1/lib/libQtGui.prl \
		/usr/local/Trolltech/Qt-4.8.1/lib/libQtCore.prl
	$(QMAKE) -o Makefile Tognazzi.pro
/usr/local/Trolltech/Qt-4.8.1/mkspecs/common/unix.conf:
/usr/local/Trolltech/Qt-4.8.1/mkspecs/common/linux.conf:
/usr/local/Trolltech/Qt-4.8.1/mkspecs/common/gcc-base.conf:
/usr/local/Trolltech/Qt-4.8.1/mkspecs/common/gcc-base-unix.conf:
/usr/local/Trolltech/Qt-4.8.1/mkspecs/common/g++-base.conf:
/usr/local/Trolltech/Qt-4.8.1/mkspecs/common/g++-unix.conf:
/usr/local/Trolltech/Qt-4.8.1/mkspecs/qconfig.pri:
/usr/local/Trolltech/Qt-4.8.1/mkspecs/modules/qt_webkit_version.pri:
/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/qt_functions.prf:
/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/qt_config.prf:
/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/exclusive_builds.prf:
/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/default_pre.prf:
/usr/local/root/include/rootlibs.pri:
/usr/local/root/include/rootcintrule.pri:
/usr/local/root/include/rootcint.pri:
/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/release.prf:
/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/default_post.prf:
/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/warn_on.prf:
/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/qt.prf:
/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/unix/thread.prf:
/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/moc.prf:
/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/resources.prf:
/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/uic.prf:
/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/yacc.prf:
/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/lex.prf:
/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/include_source_dir.prf:
/usr/local/Trolltech/Qt-4.8.1/lib/libQtGui.prl:
/usr/local/Trolltech/Qt-4.8.1/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile Tognazzi.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Tognazzi1.0.0 || $(MKDIR) .tmp/Tognazzi1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Tognazzi1.0.0/ && $(COPY_FILE) --parents mainwindow.h variableshandler.h filereader.h scurveanalysis.h vtrimadjuster.h vtrimgain.h vtrimset.h pixelselection.h pixelsingle.h umessanger.h pixelselectionbutton.h finetuner.h .tmp/Tognazzi1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp variableshandler.cpp filereader.cpp scurveanalysis.cpp vtrimadjuster.cpp vtrimgain.cpp vtrimset.cpp pixelselection.cpp pixelsingle.cpp umessanger.cpp pixelselectionbutton.cpp finetuner.cpp .tmp/Tognazzi1.0.0/ && $(COPY_FILE) --parents mainwindow.ui pixelselection.ui pixelsingle.ui finetuner.ui .tmp/Tognazzi1.0.0/ && (cd `dirname .tmp/Tognazzi1.0.0` && $(TAR) Tognazzi1.0.0.tar Tognazzi1.0.0 && $(COMPRESS) Tognazzi1.0.0.tar) && $(MOVE) `dirname .tmp/Tognazzi1.0.0`/Tognazzi1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Tognazzi1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_pixelselection.cpp moc_pixelsingle.cpp moc_pixelselectionbutton.cpp moc_finetuner.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_pixelselection.cpp moc_pixelsingle.cpp moc_pixelselectionbutton.cpp moc_finetuner.cpp
moc_mainwindow.cpp: variableshandler.h \
		$(ROOTSYS)/include/TTree.h \
		/usr/local/root/include/TBranch.h \
		/usr/local/root/include/TNamed.h \
		/usr/local/root/include/TObject.h \
		/usr/local/root/include/Rtypes.h \
		/usr/local/root/include/RConfig.h \
		/usr/local/root/include/RVersion.h \
		/usr/local/root/include/DllImport.h \
		/usr/local/root/include/Rtypeinfo.h \
		/usr/local/root/include/TGenericClassInfo.h \
		/usr/local/root/include/TSchemaHelper.h \
		/usr/local/root/include/TStorage.h \
		/usr/local/root/include/TVersionCheck.h \
		/usr/local/root/include/Riosfwd.h \
		/usr/local/root/include/TBuffer.h \
		/usr/local/root/include/TString.h \
		/usr/local/root/include/TRefCnt.h \
		/usr/local/root/include/TMathBase.h \
		/usr/local/root/include/TObjArray.h \
		/usr/local/root/include/TSeqCollection.h \
		/usr/local/root/include/TCollection.h \
		/usr/local/root/include/TIterator.h \
		/usr/local/root/include/TAttFill.h \
		/usr/local/root/include/TAttLine.h \
		/usr/local/root/include/TAttMarker.h \
		/usr/local/root/include/TArrayD.h \
		/usr/local/root/include/TArray.h \
		/usr/local/root/include/TArrayI.h \
		/usr/local/root/include/TDataType.h \
		/usr/local/root/include/TDictionary.h \
		/usr/local/root/include/Property.h \
		/usr/local/root/include/TClass.h \
		/usr/local/root/include/TObjString.h \
		/usr/local/root/include/TVirtualTreePlayer.h \
		filereader.h \
		$(ROOTSYS)/include/TFile.h \
		/usr/local/root/include/TDirectoryFile.h \
		/usr/local/root/include/TDirectory.h \
		/usr/local/root/include/TList.h \
		/usr/local/root/include/TDatime.h \
		/usr/local/root/include/TUUID.h \
		/usr/local/root/include/TUrl.h \
		/usr/local/root/include/TMap.h \
		/usr/local/root/include/THashTable.h \
		$(ROOTSYS)/include/TH1F.h \
		/usr/local/root/include/TH1.h \
		/usr/local/root/include/TAxis.h \
		/usr/local/root/include/TAttAxis.h \
		/usr/local/root/include/TArrayC.h \
		/usr/local/root/include/TArrayS.h \
		/usr/local/root/include/TArrayF.h \
		/usr/local/root/include/Foption.h \
		/usr/local/root/include/TVectorFfwd.h \
		/usr/local/root/include/TVectorDfwd.h \
		/usr/local/root/include/TFitResultPtr.h \
		$(ROOTSYS)/include/TH2F.h \
		/usr/local/root/include/TH2.h \
		/usr/local/root/include/TMatrixFBasefwd.h \
		/usr/local/root/include/TMatrixDBasefwd.h \
		$(ROOTSYS)/include/TF1.h \
		/usr/local/root/include/TFormula.h \
		/usr/local/root/include/TBits.h \
		/usr/local/root/include/Math/ParamFunctor.h \
		umessanger.h \
		scurveanalysis.h \
		vtrimadjuster.h \
		$(ROOTSYS)/include/TGraphErrors.h \
		/usr/local/root/include/TGraph.h \
		pixelselection.h \
		pixelsingle.h \
		finetuner.h \
		mainwindow.h
	/usr/local/Trolltech/Qt-4.8.1/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_pixelselection.cpp: filereader.h \
		$(ROOTSYS)/include/TFile.h \
		/usr/local/root/include/TDirectoryFile.h \
		/usr/local/root/include/TDirectory.h \
		/usr/local/root/include/TNamed.h \
		/usr/local/root/include/TObject.h \
		/usr/local/root/include/Rtypes.h \
		/usr/local/root/include/RConfig.h \
		/usr/local/root/include/RVersion.h \
		/usr/local/root/include/DllImport.h \
		/usr/local/root/include/Rtypeinfo.h \
		/usr/local/root/include/TGenericClassInfo.h \
		/usr/local/root/include/TSchemaHelper.h \
		/usr/local/root/include/TStorage.h \
		/usr/local/root/include/TVersionCheck.h \
		/usr/local/root/include/Riosfwd.h \
		/usr/local/root/include/TBuffer.h \
		/usr/local/root/include/TString.h \
		/usr/local/root/include/TRefCnt.h \
		/usr/local/root/include/TMathBase.h \
		/usr/local/root/include/TList.h \
		/usr/local/root/include/TSeqCollection.h \
		/usr/local/root/include/TCollection.h \
		/usr/local/root/include/TIterator.h \
		/usr/local/root/include/TDatime.h \
		/usr/local/root/include/TUUID.h \
		/usr/local/root/include/TUrl.h \
		/usr/local/root/include/TMap.h \
		/usr/local/root/include/THashTable.h \
		$(ROOTSYS)/include/TTree.h \
		/usr/local/root/include/TBranch.h \
		/usr/local/root/include/TObjArray.h \
		/usr/local/root/include/TAttFill.h \
		/usr/local/root/include/TAttLine.h \
		/usr/local/root/include/TAttMarker.h \
		/usr/local/root/include/TArrayD.h \
		/usr/local/root/include/TArray.h \
		/usr/local/root/include/TArrayI.h \
		/usr/local/root/include/TDataType.h \
		/usr/local/root/include/TDictionary.h \
		/usr/local/root/include/Property.h \
		/usr/local/root/include/TClass.h \
		/usr/local/root/include/TObjString.h \
		/usr/local/root/include/TVirtualTreePlayer.h \
		$(ROOTSYS)/include/TH1F.h \
		/usr/local/root/include/TH1.h \
		/usr/local/root/include/TAxis.h \
		/usr/local/root/include/TAttAxis.h \
		/usr/local/root/include/TArrayC.h \
		/usr/local/root/include/TArrayS.h \
		/usr/local/root/include/TArrayF.h \
		/usr/local/root/include/Foption.h \
		/usr/local/root/include/TVectorFfwd.h \
		/usr/local/root/include/TVectorDfwd.h \
		/usr/local/root/include/TFitResultPtr.h \
		$(ROOTSYS)/include/TH2F.h \
		/usr/local/root/include/TH2.h \
		/usr/local/root/include/TMatrixFBasefwd.h \
		/usr/local/root/include/TMatrixDBasefwd.h \
		$(ROOTSYS)/include/TF1.h \
		/usr/local/root/include/TFormula.h \
		/usr/local/root/include/TBits.h \
		/usr/local/root/include/Math/ParamFunctor.h \
		umessanger.h \
		pixelsingle.h \
		pixelselection.h
	/usr/local/Trolltech/Qt-4.8.1/bin/moc $(DEFINES) $(INCPATH) pixelselection.h -o moc_pixelselection.cpp

moc_pixelsingle.cpp: pixelsingle.h
	/usr/local/Trolltech/Qt-4.8.1/bin/moc $(DEFINES) $(INCPATH) pixelsingle.h -o moc_pixelsingle.cpp

moc_pixelselectionbutton.cpp: pixelselectionbutton.h
	/usr/local/Trolltech/Qt-4.8.1/bin/moc $(DEFINES) $(INCPATH) pixelselectionbutton.h -o moc_pixelselectionbutton.cpp

moc_finetuner.cpp: finetuner.h
	/usr/local/Trolltech/Qt-4.8.1/bin/moc $(DEFINES) $(INCPATH) finetuner.h -o moc_finetuner.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_pixelselection.h ui_pixelsingle.h ui_finetuner.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_pixelselection.h ui_pixelsingle.h ui_finetuner.h
ui_mainwindow.h: mainwindow.ui
	/usr/local/Trolltech/Qt-4.8.1/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_pixelselection.h: pixelselection.ui
	/usr/local/Trolltech/Qt-4.8.1/bin/uic pixelselection.ui -o ui_pixelselection.h

ui_pixelsingle.h: pixelsingle.ui
	/usr/local/Trolltech/Qt-4.8.1/bin/uic pixelsingle.ui -o ui_pixelsingle.h

ui_finetuner.h: finetuner.ui
	/usr/local/Trolltech/Qt-4.8.1/bin/uic finetuner.ui -o ui_finetuner.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		variableshandler.h \
		$(ROOTSYS)/include/TTree.h \
		/usr/local/root/include/TBranch.h \
		/usr/local/root/include/TNamed.h \
		/usr/local/root/include/TObject.h \
		/usr/local/root/include/Rtypes.h \
		/usr/local/root/include/RConfig.h \
		/usr/local/root/include/RVersion.h \
		/usr/local/root/include/DllImport.h \
		/usr/local/root/include/Rtypeinfo.h \
		/usr/local/root/include/TGenericClassInfo.h \
		/usr/local/root/include/TSchemaHelper.h \
		/usr/local/root/include/TStorage.h \
		/usr/local/root/include/TVersionCheck.h \
		/usr/local/root/include/Riosfwd.h \
		/usr/local/root/include/TBuffer.h \
		/usr/local/root/include/TString.h \
		/usr/local/root/include/TRefCnt.h \
		/usr/local/root/include/TMathBase.h \
		/usr/local/root/include/TObjArray.h \
		/usr/local/root/include/TSeqCollection.h \
		/usr/local/root/include/TCollection.h \
		/usr/local/root/include/TIterator.h \
		/usr/local/root/include/TAttFill.h \
		/usr/local/root/include/TAttLine.h \
		/usr/local/root/include/TAttMarker.h \
		/usr/local/root/include/TArrayD.h \
		/usr/local/root/include/TArray.h \
		/usr/local/root/include/TArrayI.h \
		/usr/local/root/include/TDataType.h \
		/usr/local/root/include/TDictionary.h \
		/usr/local/root/include/Property.h \
		/usr/local/root/include/TClass.h \
		/usr/local/root/include/TObjString.h \
		/usr/local/root/include/TVirtualTreePlayer.h \
		filereader.h \
		$(ROOTSYS)/include/TFile.h \
		/usr/local/root/include/TDirectoryFile.h \
		/usr/local/root/include/TDirectory.h \
		/usr/local/root/include/TList.h \
		/usr/local/root/include/TDatime.h \
		/usr/local/root/include/TUUID.h \
		/usr/local/root/include/TUrl.h \
		/usr/local/root/include/TMap.h \
		/usr/local/root/include/THashTable.h \
		$(ROOTSYS)/include/TH1F.h \
		/usr/local/root/include/TH1.h \
		/usr/local/root/include/TAxis.h \
		/usr/local/root/include/TAttAxis.h \
		/usr/local/root/include/TArrayC.h \
		/usr/local/root/include/TArrayS.h \
		/usr/local/root/include/TArrayF.h \
		/usr/local/root/include/Foption.h \
		/usr/local/root/include/TVectorFfwd.h \
		/usr/local/root/include/TVectorDfwd.h \
		/usr/local/root/include/TFitResultPtr.h \
		$(ROOTSYS)/include/TH2F.h \
		/usr/local/root/include/TH2.h \
		/usr/local/root/include/TMatrixFBasefwd.h \
		/usr/local/root/include/TMatrixDBasefwd.h \
		$(ROOTSYS)/include/TF1.h \
		/usr/local/root/include/TFormula.h \
		/usr/local/root/include/TBits.h \
		/usr/local/root/include/Math/ParamFunctor.h \
		umessanger.h \
		scurveanalysis.h \
		vtrimadjuster.h \
		$(ROOTSYS)/include/TGraphErrors.h \
		/usr/local/root/include/TGraph.h \
		pixelselection.h \
		pixelsingle.h \
		finetuner.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		variableshandler.h \
		$(ROOTSYS)/include/TTree.h \
		/usr/local/root/include/TBranch.h \
		/usr/local/root/include/TNamed.h \
		/usr/local/root/include/TObject.h \
		/usr/local/root/include/Rtypes.h \
		/usr/local/root/include/RConfig.h \
		/usr/local/root/include/RVersion.h \
		/usr/local/root/include/DllImport.h \
		/usr/local/root/include/Rtypeinfo.h \
		/usr/local/root/include/TGenericClassInfo.h \
		/usr/local/root/include/TSchemaHelper.h \
		/usr/local/root/include/TStorage.h \
		/usr/local/root/include/TVersionCheck.h \
		/usr/local/root/include/Riosfwd.h \
		/usr/local/root/include/TBuffer.h \
		/usr/local/root/include/TString.h \
		/usr/local/root/include/TRefCnt.h \
		/usr/local/root/include/TMathBase.h \
		/usr/local/root/include/TObjArray.h \
		/usr/local/root/include/TSeqCollection.h \
		/usr/local/root/include/TCollection.h \
		/usr/local/root/include/TIterator.h \
		/usr/local/root/include/TAttFill.h \
		/usr/local/root/include/TAttLine.h \
		/usr/local/root/include/TAttMarker.h \
		/usr/local/root/include/TArrayD.h \
		/usr/local/root/include/TArray.h \
		/usr/local/root/include/TArrayI.h \
		/usr/local/root/include/TDataType.h \
		/usr/local/root/include/TDictionary.h \
		/usr/local/root/include/Property.h \
		/usr/local/root/include/TClass.h \
		/usr/local/root/include/TObjString.h \
		/usr/local/root/include/TVirtualTreePlayer.h \
		filereader.h \
		$(ROOTSYS)/include/TFile.h \
		/usr/local/root/include/TDirectoryFile.h \
		/usr/local/root/include/TDirectory.h \
		/usr/local/root/include/TList.h \
		/usr/local/root/include/TDatime.h \
		/usr/local/root/include/TUUID.h \
		/usr/local/root/include/TUrl.h \
		/usr/local/root/include/TMap.h \
		/usr/local/root/include/THashTable.h \
		$(ROOTSYS)/include/TH1F.h \
		/usr/local/root/include/TH1.h \
		/usr/local/root/include/TAxis.h \
		/usr/local/root/include/TAttAxis.h \
		/usr/local/root/include/TArrayC.h \
		/usr/local/root/include/TArrayS.h \
		/usr/local/root/include/TArrayF.h \
		/usr/local/root/include/Foption.h \
		/usr/local/root/include/TVectorFfwd.h \
		/usr/local/root/include/TVectorDfwd.h \
		/usr/local/root/include/TFitResultPtr.h \
		$(ROOTSYS)/include/TH2F.h \
		/usr/local/root/include/TH2.h \
		/usr/local/root/include/TMatrixFBasefwd.h \
		/usr/local/root/include/TMatrixDBasefwd.h \
		$(ROOTSYS)/include/TF1.h \
		/usr/local/root/include/TFormula.h \
		/usr/local/root/include/TBits.h \
		/usr/local/root/include/Math/ParamFunctor.h \
		umessanger.h \
		scurveanalysis.h \
		vtrimadjuster.h \
		$(ROOTSYS)/include/TGraphErrors.h \
		/usr/local/root/include/TGraph.h \
		pixelselection.h \
		pixelsingle.h \
		finetuner.h \
		ui_mainwindow.h \
		$(ROOTSYS)/include/TQtWidget.h \
		/usr/local/root/include/TCanvas.h \
		/usr/local/root/include/TPad.h \
		/usr/local/root/include/TVirtualPad.h \
		/usr/local/root/include/TAttPad.h \
		/usr/local/root/include/TVirtualX.h \
		/usr/local/root/include/TAttText.h \
		/usr/local/root/include/GuiTypes.h \
		/usr/local/root/include/Buttons.h \
		/usr/local/root/include/TQObject.h \
		/usr/local/root/include/TQClass.h \
		/usr/local/root/include/TAttCanvas.h \
		/usr/local/root/include/TCanvasImp.h \
		vtrimgain.h \
		vtrimset.h \
		$(ROOTSYS)/include/TStyle.h \
		$(ROOTSYS)/include/TGraph2D.h \
		/usr/local/root/include/TVirtualHistPainter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

variableshandler.o: variableshandler.cpp variableshandler.h \
		$(ROOTSYS)/include/TTree.h \
		/usr/local/root/include/TBranch.h \
		/usr/local/root/include/TNamed.h \
		/usr/local/root/include/TObject.h \
		/usr/local/root/include/Rtypes.h \
		/usr/local/root/include/RConfig.h \
		/usr/local/root/include/RVersion.h \
		/usr/local/root/include/DllImport.h \
		/usr/local/root/include/Rtypeinfo.h \
		/usr/local/root/include/TGenericClassInfo.h \
		/usr/local/root/include/TSchemaHelper.h \
		/usr/local/root/include/TStorage.h \
		/usr/local/root/include/TVersionCheck.h \
		/usr/local/root/include/Riosfwd.h \
		/usr/local/root/include/TBuffer.h \
		/usr/local/root/include/TString.h \
		/usr/local/root/include/TRefCnt.h \
		/usr/local/root/include/TMathBase.h \
		/usr/local/root/include/TObjArray.h \
		/usr/local/root/include/TSeqCollection.h \
		/usr/local/root/include/TCollection.h \
		/usr/local/root/include/TIterator.h \
		/usr/local/root/include/TAttFill.h \
		/usr/local/root/include/TAttLine.h \
		/usr/local/root/include/TAttMarker.h \
		/usr/local/root/include/TArrayD.h \
		/usr/local/root/include/TArray.h \
		/usr/local/root/include/TArrayI.h \
		/usr/local/root/include/TDataType.h \
		/usr/local/root/include/TDictionary.h \
		/usr/local/root/include/Property.h \
		/usr/local/root/include/TClass.h \
		/usr/local/root/include/TObjString.h \
		/usr/local/root/include/TVirtualTreePlayer.h \
		filereader.h \
		$(ROOTSYS)/include/TFile.h \
		/usr/local/root/include/TDirectoryFile.h \
		/usr/local/root/include/TDirectory.h \
		/usr/local/root/include/TList.h \
		/usr/local/root/include/TDatime.h \
		/usr/local/root/include/TUUID.h \
		/usr/local/root/include/TUrl.h \
		/usr/local/root/include/TMap.h \
		/usr/local/root/include/THashTable.h \
		$(ROOTSYS)/include/TH1F.h \
		/usr/local/root/include/TH1.h \
		/usr/local/root/include/TAxis.h \
		/usr/local/root/include/TAttAxis.h \
		/usr/local/root/include/TArrayC.h \
		/usr/local/root/include/TArrayS.h \
		/usr/local/root/include/TArrayF.h \
		/usr/local/root/include/Foption.h \
		/usr/local/root/include/TVectorFfwd.h \
		/usr/local/root/include/TVectorDfwd.h \
		/usr/local/root/include/TFitResultPtr.h \
		$(ROOTSYS)/include/TH2F.h \
		/usr/local/root/include/TH2.h \
		/usr/local/root/include/TMatrixFBasefwd.h \
		/usr/local/root/include/TMatrixDBasefwd.h \
		$(ROOTSYS)/include/TF1.h \
		/usr/local/root/include/TFormula.h \
		/usr/local/root/include/TBits.h \
		/usr/local/root/include/Math/ParamFunctor.h \
		umessanger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o variableshandler.o variableshandler.cpp

filereader.o: filereader.cpp filereader.h \
		$(ROOTSYS)/include/TFile.h \
		/usr/local/root/include/TDirectoryFile.h \
		/usr/local/root/include/TDirectory.h \
		/usr/local/root/include/TNamed.h \
		/usr/local/root/include/TObject.h \
		/usr/local/root/include/Rtypes.h \
		/usr/local/root/include/RConfig.h \
		/usr/local/root/include/RVersion.h \
		/usr/local/root/include/DllImport.h \
		/usr/local/root/include/Rtypeinfo.h \
		/usr/local/root/include/TGenericClassInfo.h \
		/usr/local/root/include/TSchemaHelper.h \
		/usr/local/root/include/TStorage.h \
		/usr/local/root/include/TVersionCheck.h \
		/usr/local/root/include/Riosfwd.h \
		/usr/local/root/include/TBuffer.h \
		/usr/local/root/include/TString.h \
		/usr/local/root/include/TRefCnt.h \
		/usr/local/root/include/TMathBase.h \
		/usr/local/root/include/TList.h \
		/usr/local/root/include/TSeqCollection.h \
		/usr/local/root/include/TCollection.h \
		/usr/local/root/include/TIterator.h \
		/usr/local/root/include/TDatime.h \
		/usr/local/root/include/TUUID.h \
		/usr/local/root/include/TUrl.h \
		/usr/local/root/include/TMap.h \
		/usr/local/root/include/THashTable.h \
		$(ROOTSYS)/include/TTree.h \
		/usr/local/root/include/TBranch.h \
		/usr/local/root/include/TObjArray.h \
		/usr/local/root/include/TAttFill.h \
		/usr/local/root/include/TAttLine.h \
		/usr/local/root/include/TAttMarker.h \
		/usr/local/root/include/TArrayD.h \
		/usr/local/root/include/TArray.h \
		/usr/local/root/include/TArrayI.h \
		/usr/local/root/include/TDataType.h \
		/usr/local/root/include/TDictionary.h \
		/usr/local/root/include/Property.h \
		/usr/local/root/include/TClass.h \
		/usr/local/root/include/TObjString.h \
		/usr/local/root/include/TVirtualTreePlayer.h \
		$(ROOTSYS)/include/TH1F.h \
		/usr/local/root/include/TH1.h \
		/usr/local/root/include/TAxis.h \
		/usr/local/root/include/TAttAxis.h \
		/usr/local/root/include/TArrayC.h \
		/usr/local/root/include/TArrayS.h \
		/usr/local/root/include/TArrayF.h \
		/usr/local/root/include/Foption.h \
		/usr/local/root/include/TVectorFfwd.h \
		/usr/local/root/include/TVectorDfwd.h \
		/usr/local/root/include/TFitResultPtr.h \
		$(ROOTSYS)/include/TH2F.h \
		/usr/local/root/include/TH2.h \
		/usr/local/root/include/TMatrixFBasefwd.h \
		/usr/local/root/include/TMatrixDBasefwd.h \
		$(ROOTSYS)/include/TF1.h \
		/usr/local/root/include/TFormula.h \
		/usr/local/root/include/TBits.h \
		/usr/local/root/include/Math/ParamFunctor.h \
		umessanger.h \
		/usr/local/root/include/TPad.h \
		/usr/local/root/include/TVirtualPad.h \
		/usr/local/root/include/TAttPad.h \
		/usr/local/root/include/TVirtualX.h \
		/usr/local/root/include/TAttText.h \
		/usr/local/root/include/GuiTypes.h \
		/usr/local/root/include/Buttons.h \
		/usr/local/root/include/TQObject.h \
		/usr/local/root/include/TQClass.h \
		$(ROOTSYS)/include/TROOT.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o filereader.o filereader.cpp

scurveanalysis.o: scurveanalysis.cpp scurveanalysis.h \
		filereader.h \
		$(ROOTSYS)/include/TFile.h \
		/usr/local/root/include/TDirectoryFile.h \
		/usr/local/root/include/TDirectory.h \
		/usr/local/root/include/TNamed.h \
		/usr/local/root/include/TObject.h \
		/usr/local/root/include/Rtypes.h \
		/usr/local/root/include/RConfig.h \
		/usr/local/root/include/RVersion.h \
		/usr/local/root/include/DllImport.h \
		/usr/local/root/include/Rtypeinfo.h \
		/usr/local/root/include/TGenericClassInfo.h \
		/usr/local/root/include/TSchemaHelper.h \
		/usr/local/root/include/TStorage.h \
		/usr/local/root/include/TVersionCheck.h \
		/usr/local/root/include/Riosfwd.h \
		/usr/local/root/include/TBuffer.h \
		/usr/local/root/include/TString.h \
		/usr/local/root/include/TRefCnt.h \
		/usr/local/root/include/TMathBase.h \
		/usr/local/root/include/TList.h \
		/usr/local/root/include/TSeqCollection.h \
		/usr/local/root/include/TCollection.h \
		/usr/local/root/include/TIterator.h \
		/usr/local/root/include/TDatime.h \
		/usr/local/root/include/TUUID.h \
		/usr/local/root/include/TUrl.h \
		/usr/local/root/include/TMap.h \
		/usr/local/root/include/THashTable.h \
		$(ROOTSYS)/include/TTree.h \
		/usr/local/root/include/TBranch.h \
		/usr/local/root/include/TObjArray.h \
		/usr/local/root/include/TAttFill.h \
		/usr/local/root/include/TAttLine.h \
		/usr/local/root/include/TAttMarker.h \
		/usr/local/root/include/TArrayD.h \
		/usr/local/root/include/TArray.h \
		/usr/local/root/include/TArrayI.h \
		/usr/local/root/include/TDataType.h \
		/usr/local/root/include/TDictionary.h \
		/usr/local/root/include/Property.h \
		/usr/local/root/include/TClass.h \
		/usr/local/root/include/TObjString.h \
		/usr/local/root/include/TVirtualTreePlayer.h \
		$(ROOTSYS)/include/TH1F.h \
		/usr/local/root/include/TH1.h \
		/usr/local/root/include/TAxis.h \
		/usr/local/root/include/TAttAxis.h \
		/usr/local/root/include/TArrayC.h \
		/usr/local/root/include/TArrayS.h \
		/usr/local/root/include/TArrayF.h \
		/usr/local/root/include/Foption.h \
		/usr/local/root/include/TVectorFfwd.h \
		/usr/local/root/include/TVectorDfwd.h \
		/usr/local/root/include/TFitResultPtr.h \
		$(ROOTSYS)/include/TH2F.h \
		/usr/local/root/include/TH2.h \
		/usr/local/root/include/TMatrixFBasefwd.h \
		/usr/local/root/include/TMatrixDBasefwd.h \
		$(ROOTSYS)/include/TF1.h \
		/usr/local/root/include/TFormula.h \
		/usr/local/root/include/TBits.h \
		/usr/local/root/include/Math/ParamFunctor.h \
		umessanger.h \
		$(ROOTSYS)/include/TMath.h \
		/usr/local/root/include/TError.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o scurveanalysis.o scurveanalysis.cpp

vtrimadjuster.o: vtrimadjuster.cpp vtrimadjuster.h \
		scurveanalysis.h \
		filereader.h \
		$(ROOTSYS)/include/TFile.h \
		/usr/local/root/include/TDirectoryFile.h \
		/usr/local/root/include/TDirectory.h \
		/usr/local/root/include/TNamed.h \
		/usr/local/root/include/TObject.h \
		/usr/local/root/include/Rtypes.h \
		/usr/local/root/include/RConfig.h \
		/usr/local/root/include/RVersion.h \
		/usr/local/root/include/DllImport.h \
		/usr/local/root/include/Rtypeinfo.h \
		/usr/local/root/include/TGenericClassInfo.h \
		/usr/local/root/include/TSchemaHelper.h \
		/usr/local/root/include/TStorage.h \
		/usr/local/root/include/TVersionCheck.h \
		/usr/local/root/include/Riosfwd.h \
		/usr/local/root/include/TBuffer.h \
		/usr/local/root/include/TString.h \
		/usr/local/root/include/TRefCnt.h \
		/usr/local/root/include/TMathBase.h \
		/usr/local/root/include/TList.h \
		/usr/local/root/include/TSeqCollection.h \
		/usr/local/root/include/TCollection.h \
		/usr/local/root/include/TIterator.h \
		/usr/local/root/include/TDatime.h \
		/usr/local/root/include/TUUID.h \
		/usr/local/root/include/TUrl.h \
		/usr/local/root/include/TMap.h \
		/usr/local/root/include/THashTable.h \
		$(ROOTSYS)/include/TTree.h \
		/usr/local/root/include/TBranch.h \
		/usr/local/root/include/TObjArray.h \
		/usr/local/root/include/TAttFill.h \
		/usr/local/root/include/TAttLine.h \
		/usr/local/root/include/TAttMarker.h \
		/usr/local/root/include/TArrayD.h \
		/usr/local/root/include/TArray.h \
		/usr/local/root/include/TArrayI.h \
		/usr/local/root/include/TDataType.h \
		/usr/local/root/include/TDictionary.h \
		/usr/local/root/include/Property.h \
		/usr/local/root/include/TClass.h \
		/usr/local/root/include/TObjString.h \
		/usr/local/root/include/TVirtualTreePlayer.h \
		$(ROOTSYS)/include/TH1F.h \
		/usr/local/root/include/TH1.h \
		/usr/local/root/include/TAxis.h \
		/usr/local/root/include/TAttAxis.h \
		/usr/local/root/include/TArrayC.h \
		/usr/local/root/include/TArrayS.h \
		/usr/local/root/include/TArrayF.h \
		/usr/local/root/include/Foption.h \
		/usr/local/root/include/TVectorFfwd.h \
		/usr/local/root/include/TVectorDfwd.h \
		/usr/local/root/include/TFitResultPtr.h \
		$(ROOTSYS)/include/TH2F.h \
		/usr/local/root/include/TH2.h \
		/usr/local/root/include/TMatrixFBasefwd.h \
		/usr/local/root/include/TMatrixDBasefwd.h \
		$(ROOTSYS)/include/TF1.h \
		/usr/local/root/include/TFormula.h \
		/usr/local/root/include/TBits.h \
		/usr/local/root/include/Math/ParamFunctor.h \
		umessanger.h \
		$(ROOTSYS)/include/TGraphErrors.h \
		/usr/local/root/include/TGraph.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o vtrimadjuster.o vtrimadjuster.cpp

vtrimgain.o: vtrimgain.cpp vtrimgain.h \
		scurveanalysis.h \
		filereader.h \
		$(ROOTSYS)/include/TFile.h \
		/usr/local/root/include/TDirectoryFile.h \
		/usr/local/root/include/TDirectory.h \
		/usr/local/root/include/TNamed.h \
		/usr/local/root/include/TObject.h \
		/usr/local/root/include/Rtypes.h \
		/usr/local/root/include/RConfig.h \
		/usr/local/root/include/RVersion.h \
		/usr/local/root/include/DllImport.h \
		/usr/local/root/include/Rtypeinfo.h \
		/usr/local/root/include/TGenericClassInfo.h \
		/usr/local/root/include/TSchemaHelper.h \
		/usr/local/root/include/TStorage.h \
		/usr/local/root/include/TVersionCheck.h \
		/usr/local/root/include/Riosfwd.h \
		/usr/local/root/include/TBuffer.h \
		/usr/local/root/include/TString.h \
		/usr/local/root/include/TRefCnt.h \
		/usr/local/root/include/TMathBase.h \
		/usr/local/root/include/TList.h \
		/usr/local/root/include/TSeqCollection.h \
		/usr/local/root/include/TCollection.h \
		/usr/local/root/include/TIterator.h \
		/usr/local/root/include/TDatime.h \
		/usr/local/root/include/TUUID.h \
		/usr/local/root/include/TUrl.h \
		/usr/local/root/include/TMap.h \
		/usr/local/root/include/THashTable.h \
		$(ROOTSYS)/include/TTree.h \
		/usr/local/root/include/TBranch.h \
		/usr/local/root/include/TObjArray.h \
		/usr/local/root/include/TAttFill.h \
		/usr/local/root/include/TAttLine.h \
		/usr/local/root/include/TAttMarker.h \
		/usr/local/root/include/TArrayD.h \
		/usr/local/root/include/TArray.h \
		/usr/local/root/include/TArrayI.h \
		/usr/local/root/include/TDataType.h \
		/usr/local/root/include/TDictionary.h \
		/usr/local/root/include/Property.h \
		/usr/local/root/include/TClass.h \
		/usr/local/root/include/TObjString.h \
		/usr/local/root/include/TVirtualTreePlayer.h \
		$(ROOTSYS)/include/TH1F.h \
		/usr/local/root/include/TH1.h \
		/usr/local/root/include/TAxis.h \
		/usr/local/root/include/TAttAxis.h \
		/usr/local/root/include/TArrayC.h \
		/usr/local/root/include/TArrayS.h \
		/usr/local/root/include/TArrayF.h \
		/usr/local/root/include/Foption.h \
		/usr/local/root/include/TVectorFfwd.h \
		/usr/local/root/include/TVectorDfwd.h \
		/usr/local/root/include/TFitResultPtr.h \
		$(ROOTSYS)/include/TH2F.h \
		/usr/local/root/include/TH2.h \
		/usr/local/root/include/TMatrixFBasefwd.h \
		/usr/local/root/include/TMatrixDBasefwd.h \
		$(ROOTSYS)/include/TF1.h \
		/usr/local/root/include/TFormula.h \
		/usr/local/root/include/TBits.h \
		/usr/local/root/include/Math/ParamFunctor.h \
		umessanger.h \
		/usr/local/root/include/TGraph.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o vtrimgain.o vtrimgain.cpp

vtrimset.o: vtrimset.cpp vtrimset.h \
		vtrimgain.h \
		scurveanalysis.h \
		filereader.h \
		$(ROOTSYS)/include/TFile.h \
		/usr/local/root/include/TDirectoryFile.h \
		/usr/local/root/include/TDirectory.h \
		/usr/local/root/include/TNamed.h \
		/usr/local/root/include/TObject.h \
		/usr/local/root/include/Rtypes.h \
		/usr/local/root/include/RConfig.h \
		/usr/local/root/include/RVersion.h \
		/usr/local/root/include/DllImport.h \
		/usr/local/root/include/Rtypeinfo.h \
		/usr/local/root/include/TGenericClassInfo.h \
		/usr/local/root/include/TSchemaHelper.h \
		/usr/local/root/include/TStorage.h \
		/usr/local/root/include/TVersionCheck.h \
		/usr/local/root/include/Riosfwd.h \
		/usr/local/root/include/TBuffer.h \
		/usr/local/root/include/TString.h \
		/usr/local/root/include/TRefCnt.h \
		/usr/local/root/include/TMathBase.h \
		/usr/local/root/include/TList.h \
		/usr/local/root/include/TSeqCollection.h \
		/usr/local/root/include/TCollection.h \
		/usr/local/root/include/TIterator.h \
		/usr/local/root/include/TDatime.h \
		/usr/local/root/include/TUUID.h \
		/usr/local/root/include/TUrl.h \
		/usr/local/root/include/TMap.h \
		/usr/local/root/include/THashTable.h \
		$(ROOTSYS)/include/TTree.h \
		/usr/local/root/include/TBranch.h \
		/usr/local/root/include/TObjArray.h \
		/usr/local/root/include/TAttFill.h \
		/usr/local/root/include/TAttLine.h \
		/usr/local/root/include/TAttMarker.h \
		/usr/local/root/include/TArrayD.h \
		/usr/local/root/include/TArray.h \
		/usr/local/root/include/TArrayI.h \
		/usr/local/root/include/TDataType.h \
		/usr/local/root/include/TDictionary.h \
		/usr/local/root/include/Property.h \
		/usr/local/root/include/TClass.h \
		/usr/local/root/include/TObjString.h \
		/usr/local/root/include/TVirtualTreePlayer.h \
		$(ROOTSYS)/include/TH1F.h \
		/usr/local/root/include/TH1.h \
		/usr/local/root/include/TAxis.h \
		/usr/local/root/include/TAttAxis.h \
		/usr/local/root/include/TArrayC.h \
		/usr/local/root/include/TArrayS.h \
		/usr/local/root/include/TArrayF.h \
		/usr/local/root/include/Foption.h \
		/usr/local/root/include/TVectorFfwd.h \
		/usr/local/root/include/TVectorDfwd.h \
		/usr/local/root/include/TFitResultPtr.h \
		$(ROOTSYS)/include/TH2F.h \
		/usr/local/root/include/TH2.h \
		/usr/local/root/include/TMatrixFBasefwd.h \
		/usr/local/root/include/TMatrixDBasefwd.h \
		$(ROOTSYS)/include/TF1.h \
		/usr/local/root/include/TFormula.h \
		/usr/local/root/include/TBits.h \
		/usr/local/root/include/Math/ParamFunctor.h \
		umessanger.h \
		/usr/local/root/include/TGraph.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o vtrimset.o vtrimset.cpp

pixelselection.o: pixelselection.cpp pixelselection.h \
		filereader.h \
		$(ROOTSYS)/include/TFile.h \
		/usr/local/root/include/TDirectoryFile.h \
		/usr/local/root/include/TDirectory.h \
		/usr/local/root/include/TNamed.h \
		/usr/local/root/include/TObject.h \
		/usr/local/root/include/Rtypes.h \
		/usr/local/root/include/RConfig.h \
		/usr/local/root/include/RVersion.h \
		/usr/local/root/include/DllImport.h \
		/usr/local/root/include/Rtypeinfo.h \
		/usr/local/root/include/TGenericClassInfo.h \
		/usr/local/root/include/TSchemaHelper.h \
		/usr/local/root/include/TStorage.h \
		/usr/local/root/include/TVersionCheck.h \
		/usr/local/root/include/Riosfwd.h \
		/usr/local/root/include/TBuffer.h \
		/usr/local/root/include/TString.h \
		/usr/local/root/include/TRefCnt.h \
		/usr/local/root/include/TMathBase.h \
		/usr/local/root/include/TList.h \
		/usr/local/root/include/TSeqCollection.h \
		/usr/local/root/include/TCollection.h \
		/usr/local/root/include/TIterator.h \
		/usr/local/root/include/TDatime.h \
		/usr/local/root/include/TUUID.h \
		/usr/local/root/include/TUrl.h \
		/usr/local/root/include/TMap.h \
		/usr/local/root/include/THashTable.h \
		$(ROOTSYS)/include/TTree.h \
		/usr/local/root/include/TBranch.h \
		/usr/local/root/include/TObjArray.h \
		/usr/local/root/include/TAttFill.h \
		/usr/local/root/include/TAttLine.h \
		/usr/local/root/include/TAttMarker.h \
		/usr/local/root/include/TArrayD.h \
		/usr/local/root/include/TArray.h \
		/usr/local/root/include/TArrayI.h \
		/usr/local/root/include/TDataType.h \
		/usr/local/root/include/TDictionary.h \
		/usr/local/root/include/Property.h \
		/usr/local/root/include/TClass.h \
		/usr/local/root/include/TObjString.h \
		/usr/local/root/include/TVirtualTreePlayer.h \
		$(ROOTSYS)/include/TH1F.h \
		/usr/local/root/include/TH1.h \
		/usr/local/root/include/TAxis.h \
		/usr/local/root/include/TAttAxis.h \
		/usr/local/root/include/TArrayC.h \
		/usr/local/root/include/TArrayS.h \
		/usr/local/root/include/TArrayF.h \
		/usr/local/root/include/Foption.h \
		/usr/local/root/include/TVectorFfwd.h \
		/usr/local/root/include/TVectorDfwd.h \
		/usr/local/root/include/TFitResultPtr.h \
		$(ROOTSYS)/include/TH2F.h \
		/usr/local/root/include/TH2.h \
		/usr/local/root/include/TMatrixFBasefwd.h \
		/usr/local/root/include/TMatrixDBasefwd.h \
		$(ROOTSYS)/include/TF1.h \
		/usr/local/root/include/TFormula.h \
		/usr/local/root/include/TBits.h \
		/usr/local/root/include/Math/ParamFunctor.h \
		umessanger.h \
		pixelsingle.h \
		ui_pixelselection.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pixelselection.o pixelselection.cpp

pixelsingle.o: pixelsingle.cpp pixelsingle.h \
		ui_pixelsingle.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pixelsingle.o pixelsingle.cpp

umessanger.o: umessanger.cpp umessanger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o umessanger.o umessanger.cpp

pixelselectionbutton.o: pixelselectionbutton.cpp pixelselectionbutton.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pixelselectionbutton.o pixelselectionbutton.cpp

finetuner.o: finetuner.cpp finetuner.h \
		ui_finetuner.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o finetuner.o finetuner.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_pixelselection.o: moc_pixelselection.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_pixelselection.o moc_pixelselection.cpp

moc_pixelsingle.o: moc_pixelsingle.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_pixelsingle.o moc_pixelsingle.cpp

moc_pixelselectionbutton.o: moc_pixelselectionbutton.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_pixelselectionbutton.o moc_pixelselectionbutton.cpp

moc_finetuner.o: moc_finetuner.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_finetuner.o moc_finetuner.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

